const fs = require('fs');
const path = require('path');

function processFile(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');

  let newContent = content;
  
  // Cleanup duplicate variants generated by earlier naive script
  newContent = newContent.replace(/dark:hover:bg-zinc-800 dark:hover:bg-zinc-200/g, 'dark:hover:bg-zinc-800');
  newContent = newContent.replace(/dark:bg-zinc-900 dark:bg-zinc-100/g, 'dark:bg-zinc-100');
  newContent = newContent.replace(/dark:hover:bg-zinc-800 dark:hover:bg-zinc-800/g, 'dark:hover:bg-zinc-800');
  newContent = newContent.replace(/dark:bg-zinc-900\/60 dark:bg-zinc-900\/60/g, 'dark:bg-zinc-900/60');
  newContent = newContent.replace(/dark:bg-zinc-100 dark:bg-zinc-100/g, 'dark:bg-zinc-100');
  newContent = newContent.replace(/dark:border-zinc-800 dark:border-zinc-800/g, 'dark:border-zinc-800');
  
  if (content !== newContent) {
    fs.writeFileSync(filePath, newContent, 'utf8');
    console.log(`Cleaned ${filePath}`);
  }
}

function traverse(dir) {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      if (file !== 'node_modules' && file !== '.next') {
        traverse(filePath);
      }
    } else if (file.endsWith('.tsx') || file.endsWith('.ts')) {
      processFile(filePath);
    }
  }
}

traverse(path.join(__dirname, 'app'));
traverse(path.join(__dirname, 'components'));
